apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:tu/p1/TnrB83gso3jwO1lFjl3VnEwlEFLU55g0EbedUtMowyncKeJAuH7dUxB/L6uj/9KssVJ/fS5/bhmCD8xHuBB7dQBIbLBd9qoMQ0pLvVPLPG/AnnKIoTjZuvn0l6W6THD4Rg+FRuYpLz3Vnn2lw+CbkWQyXwvNWrCDkVKRD3,iv:ojBgAx9eLmYXTITPZ+IoKm+toOYd1tEGJS5TDE2nzJM=,tag:+s1mfcDqrwoCpVRDPer3MQ==,type:str]
sops:
    age:
        - recipient: age1jsxzylyaxjj52rjkla5gvcdxyk52udp5vahrtpfxvet2th2p0uvq0263ye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXekIvd3Y2YnFIQlJndjUv
            MW8xd3BSVEhHQXFVRmV4L1NXaFVMTmxEWTMwCkhtQU94WkcrVWU2YkxKZDlTWm93
            cFhLSER5Q0U4dWJOMk02Rm9RTnZpUzAKLS0tIFZGeVZzSW1ndEVGaG5xODcrZnV4
            bWFzTHVXMVpqRmgxK1NCMmhsd0NRa1UKXFRrsn4Zy5bOopNE4RlrWcks1EqX1uVE
            VK1VPMwLdDMAtwWF9EpwqWwly6IAAytM1fAIhsthZfVt9dHrToIYsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T16:08:28Z"
    mac: ENC[AES256_GCM,data:s+SGNDh/ay8nFvZusJrLxrGx+Jamp4mAjrltQTHSz+xu++X/97nkK9kJirMGRh3y3ty3mXtGd22E/QJLrn3exri+A2sIy3R69RGrPOokdtkyjAateFwaHK2b2YaOww+FWQ+sH0U9eQPg/+gG4tKIH8XI+d7TrAj4GXjVWkzB9os=,iv:2O8y3LRUCgj2FcymI2Q89GcNyBoRvL3sQB+d2Wzlz4I=,tag:wQ2fZ0tMi3mN8MiDttwY0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
