apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 10m
  chart:
    spec:
      chart: velero
      version: "6.5.0"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system

  install:
    createNamespace: false

  values:
    configuration: {}

    backupStorageLocations:
      - name: azure
        provider: azure
        bucket: velero-backups
        prefix: backups
        config:
          resourceGroup: homelab-rg
          storageAccount: homelabstorage100
          storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY

    credentials:
      useSecret: true
      existingSecret: cloud-credentials
      existingSecretKey: cloud
    deployNodeAgent: true
    nodeAgent:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 512Mi
    initContainers:
      - name: velero-plugin-for-microsoft-azure
        image: velero/velero-plugin-for-microsoft-azure:v1.9.0
        volumeMounts:
          - mountPath: /target
            name: plugins

    upgradeCRDs:
      image:
        repository: docker.io/bitnami/kubectl
        tag: "1.32"
        pullPolicy: IfNotPresent
