apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 10m
  chart:
    spec:
      chart: velero
      version: "6.5.0"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system

  install:
    createNamespace: false

  values:
    # Credentials (secret with SOPS)
    credentials:
      useSecret: true
      existingSecret: cloud-credentials
      existingSecretKey: cloud

    # NODE AGENT (restic replacement)
    deployNodeAgent: true

    nodeAgent:
      podSecurityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"

    # Azure plugin sidecar
    initContainers:
      - name: velero-plugin-for-microsoft-azure
        image: velero/velero-plugin-for-microsoft-azure:v1.13.1
        volumeMounts:
          - mountPath: /target
            name: plugins

    # Fix Bitnami kubectl tag used by upgradeCRDs job
    upgradeCRDs:
      image:
        repository: docker.io/bitnami/kubectl
        tag: "1.32"
        pullPolicy: IfNotPresent
