apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "79.*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

  install:
    crds: Create
  upgrade:
    crds: CreateReplace

  values:
    grafana:
      enabled: true
      service:
        type: ClusterIP
      adminPassword: "grafanaAdmin123!"  # move to KV+CSI later

    prometheus:
      service:
        type: ClusterIP

    alertmanager:
      enabled: true
      service:
        type: ClusterIP