apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
  namespace: vikunja
type: Opaque
stringData:
  VIKUNJA_DATABASE_USER: "postress-dbadmin"
  VIKUNJA_DATABASE_PASSWORD: "vikunja-postress-key"
  VIKUNJA_JWT_SECRET: "for-vikunja-jwt-secret"