apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-kv-spc
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "gbenehomelab-kv"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: grafana-admin-password
          objectType: secret
          objectVersion: ""           # latest
    tenantId: "ba029c1d-58e1-4be4-bb32-9d5db27ed57a"

  secretObjects:
    - secretName: grafana-admin-secret
      type: Opaque
      data:
        - objectName: grafana-admin-password
          key: admin-password