apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "79.*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

  install:
    crds: Create
  upgrade:
    crds: CreateReplace

  values:
    grafana:
      enabled: true
      service:
        type: ClusterIP
      admin:
        existingSecret: grafana-admin-credentials
        userKey: admin-user
        passwordKey: admin-password
      persistence:
        enabled: true
        type: pvc
        accessModes:
          - ReadWriteOnce
        size: 5Gi

    prometheus:
      service:
        type: ClusterIP
      prometheusSpec:
        retention: 15d
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi

    alertmanager:
      enabled: true
      service:
        type: ClusterIP
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
