apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vikunja
  namespace: vikunja
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - vikunja
  selector:
    matchLabels:
      app: vikunja
  endpoints:
    - interval: 30s
      path: /api/v1/metrics
      port: http
