apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
  namespace: vikunja
type: Opaque
stringData:
  POSTGRES_DB: vikunja
  POSTGRES_USER: vikunja
  POSTGRES_PASSWORD: changeme-db-password
  VIKUNJA_SERVICE_JWTSECRET: "changeme-super-secret-jwt"
