apiVersion: v1
kind: Secret
metadata:
  name: vikunja-secret
  namespace: vikunja 
type: Opaque
stringData:
  POSTGRES_DB: vikunja-db
  POSTGRES_USER: vikunja-db-admin
  POSTGRES_PASSWORD: vikunja-db-password
  VIKUNJA_SERVICE_JWTSECRET: "super-secret-jwt"
